spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/adsOnTrafficLights
    username: root
    password: rootdb
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    org.springframework: 
  file:
    name: /var/log/adsOnTrafficLights/debug.log

kafka:
  producer:
    bootstrap-servers: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
  consumer:
    bootstrap-servers: localhost:9092
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    group-id: my-group
    auto-offset-reset: earliest